import type { Metadata, Viewport } from "next";
import "../styles/globals.css";
import { montserrat_alt } from "@/styles/fonts";
import { ProviderUser } from "@/common/providers/get-user";
import { CreateTaskDialog } from "@/page/(auth)/tasks/modals/create-task";

export const metadata: Metadata = {
  title: "Telegram App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no, user-scalable=no"/>
        <link href="https://cdn.syncfusion.com/ej2/27.1.48/fluent2.css" rel="stylesheet"/>
      </head>
      <body className={montserrat_alt.className}>
        {children}
        <ProviderUser/>
        <CreateTaskDialog/>
      </body>
    </html>
  );
}
