name: Deploy project
on:
  workflow_run:
    workflows: ["Build Application"]
    types:
      - completed

jobs: 
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build
          path: ./build

      - name: Deploy to server
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        run: |
          scp -r ./build $SERVER_USER@$SERVER_HOST:/app/frontend/CTemplace-next
          ssh $SERVER_USER@$SERVER_HOST 'bash -s' < ./app/scripts/deploy.sh